### ISSUE TITLE
作者您好，关于数据维度请教。

### ISSUE THREAD

**Issue by LiRoc007** [ILoveU3D/Astra-toolbox-Cone-templete#1]
Hi，作者您好。
在使用Matlab版本的Astra的时，投影数据的维度为[探测器U，投影角度数，探测器V]，请问您的这个C++接口版本也是遵循这样的原则吗？还是[探测器U，探测器V， 投影角度]这样的形式？

**Comment by ILoveU3D** [comment]
你好，还是astra原来的格式，因为这就是astra的底层调用

**Comment by LiRoc007** [comment]
> 你好，还是astra原来的格式，因为这就是astra的底层调用

嗯嗯，谢谢。
